In [8]:
a=10
b=15
c=a*b
d=a+b
print(c,d)

150 25


In [26]:
# without passing the arguments
def cal():
    a=10
    b=30
    c=a+b
    d=a*b
    return(c,d)
cal()

(40, 300)

In [24]:
# passing the arguments 
def cal(a,b):
    c=a+b
    d=a*b
    print(c,d)
cal(20,30)

50 600


In [37]:
#statically giving the list and sum the values
l=[1,2,3,4,5]
def sum_list():
    sum=0
    for i in range(0,len(l)):
        sum=sum+l[i]
    print(sum)
sum_list()

15


In [68]:
# passing the list of elemets in the runtime by calling the function(dynamically)
def sum_list(l):
    sum=0
    for i in range(0,len(l)):
        sum=sum+l[i]
    print(sum)
sum_list([1,3,5,6,8,9])

32


In [64]:
# we cannot assign value to the global variable
def sum_list(l): 
    for i in range(0,len(l)):
        global sum    # it will re-execute and adding the previous value to the present elements
        sum=sum+l[i]
    print(sum)
sum_list([1,2,3,4])

213


In [71]:
x,y=4,5 # global variables 

(lambda x,y :x+y)(5,5)   # (5,5)are local variables so it takes the first preference to execute

10

In [72]:
(lambda x,y : x+y)(10,20) #addition

30

In [89]:
# in lambda functions there is no print and return funtions  


(lambda x : x*x)(6)   #multiplication

36

In [75]:
(lambda x,y  : x//y) (300,10)

30

In [77]:
# 

l=[1,2,3,4,5]
res=[]
for i in l:
    if i>2:
        res.append(i)
print(res)

[3, 4, 5]


In [97]:
#using lambda functions and passing the list using filters

list(filter(lambda i :i>2,[1,2,3,4,5]))
    

[3, 4, 5]

In [100]:
list(map(lambda x: x**2,[2,5]))

[4, 25]

In [103]:
l1=[1,2,3,4,5]
l2=[6,7,8,9,10]
(list(map(lambda x,y :x+y, l1,l2)))

[7, 9, 11, 13, 15]

In [10]:
from functools import reduce
reduce((lambda x,y : x+y),[1,2,3,4,5,6,7,8,9,10])

55

In [26]:
(list(map((lambda x : x**2),[1,2,3,4,5])))

[1, 4, 9, 16, 25]

In [32]:
# SQUARES OF THE LIST

l=[1,2,3]
list(map(lambda x:x**2,l))


[1, 4, 9]

In [30]:
#COMAPRE TWO LISTS
(map((lambda x,y:x if x<y else y),l,l2))

[1, 2, 3]

In [33]:
!pip install numpy          # *****to install numpy *******

In [34]:
import numpy as np          # to import numpy modules


In [35]:
my_list=[1,2,3,4,5]
my_list


[1, 2, 3, 4, 5]

In [39]:
a1=np.array([1,2,3,4,5])
a2=np.array([2,3,4,5,6])
a1+a2

array([ 3,  5,  7,  9, 11])

In [40]:
a1=np.array([1,2,3,4,5])
a1


array([1, 2, 3, 4, 5])

In [41]:
a1=np.array([1,2,3,4,5])
a1*2

array([ 2,  4,  6,  8, 10])

In [45]:
l1=np.array([1,2,3])
l2=np.array([4,5,6])
l3=l1+l2
l3

array([5, 7, 9])

In [50]:
l=[1,2,[3,4]]
l

[1, 2, [3, 4]]

In [52]:
a=np.array([[1,2,3],[2,4,5]])
a

array([[1, 2, 3],
       [2, 4, 5]])

In [53]:
a=np.array([[1,2],[2,3,4,5],[3,4,5]])
a

array([list([1, 2]), list([2, 3, 4, 5]), list([3, 4, 5])], dtype=object)

In [3]:
#declaring lists

import time
import numpy as np

l1=[1,2,3]
l2=[3,4,5]

# declaring arrays
arr1=np.array([1,2,3])
arr2=np.array([3,4,5])
initialTime=time.time()

In [4]:
initialTime=time.time()

In [5]:
import time
resultantList=[(a*b) for a,b in zip(l1,l2)]
print("time taken by numpy arrays to perform multiplication:",(time.time()-initialTime),"seconds")

time taken by numpy arrays to perform multiplication: 5.317140817642212 seconds


In [7]:
resultantArray=arr1*arr2

In [8]:
print(resultantArray)

[ 3  8 15]
