In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [ ]:
import numpy as np


#creating as simple array in numpy

arr=np.array([1,2,3,4])



In [3]:
import numpy as np

l=[1,2,3,4,5,6,7]
print(type(l))
arr=np.array(l)
print(type(arr))
print("list: ",l)
print("NP arr: ",arr)

<class 'list'>
<class 'numpy.ndarray'>
list:  [1, 2, 3, 4, 5, 6, 7]
NP arr:  [1 2 3 4 5 6 7]


In [ ]:
# nd array is called as "n-dimensional"

In [4]:
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
arr=np.arange(10)
print(arr)
print(type(arr))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [6]:
%%time
arr=np.arange(1000000)
arr=arr*arr

Wall time: 21.6 ms


In [7]:
%%time
lst=list(range(1000000))
for i in range(1000000):
    lst[i]*=lst[i]

Wall time: 198 ms


In [11]:
import numpy as np

arr=np.array([1,2,3,4])

print(arr.ndim)  #print no of dimensions

print(arr.shape)  #print shape

print(len(arr)) # print length

print(arr.dtype)  #print datatype

print(arr.itemsize)  #print item size in byte of each element

1
(4,)
4
int32
4


In [14]:
arr=np.array([[1,2,3],[4,5,6]])

print(arr)

print(arr.ndim)  #print no of dimensions

print(arr.shape)  #print shape

print(len(arr)) # print length

print(arr.dtype)  #print datatype

print(arr.itemsize)  #print item size in byte of each element

print(np.diag(arr))

[[1 2 3]
 [4 5 6]]
2
(2, 3)
2
int32
4
[1 5]


In [ ]:
FUNCTIONS OD CREATING ARRAY

In [15]:
arr=np.ones((3,3))
print(arr)
print(arr.dtype)
print(arr.itemsize)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
float64
8


In [16]:
arr=np.zeros((3,3))
print(arr)
print(arr.dtype)
print(arr.itemsize)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64
8


In [17]:
arr=np.eye(3)
print(arr)
print(arr.dtype)
print(arr.itemsize)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
float64
8


In [18]:
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
arr=np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [20]:
arr=np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


# NUMPY RANDOM NUMBERS

np.random.rand: generates an array with random number uniformly distribute between o and 1.

np.random.randn:  generates an array with random numbers normally distributed,mean=0 and stdev=1

np.random.randint: generates an array with random numbers(int) uniformly distribute between o and given number.


np.random.uniform: generates an array with random numbers(float) between given numbers.


In [2]:
import numpy as np
print(np.random.rand(10,2))

[[0.2956553  0.15613817]
 [0.88741066 0.55766849]
 [0.53776333 0.70353408]
 [0.82054719 0.63393771]
 [0.16142946 0.58297149]
 [0.01380562 0.57726985]
 [0.40646944 0.8608334 ]
 [0.41498222 0.94459379]
 [0.96375165 0.50483427]
 [0.63361867 0.31551027]]


In [3]:
print(np.random.randn(5,4))

[[ 0.18026443 -0.33982423  0.87777006  1.13322623]
 [ 0.27483355 -1.86274804  0.60404798  0.03435403]
 [ 1.01990398 -1.0098831  -1.83031855  0.89279453]
 [ 0.4596507  -0.73591656 -1.20744397 -0.04515036]
 [ 0.69063201  1.15839141 -0.79291442 -1.54108446]]


In [4]:
print(np.random.randint(10,40,size=(5,4)))

[[38 26 22 31]
 [39 11 35 11]
 [30 16 22 34]
 [36 28 37 24]
 [23 10 29 36]]


In [5]:
print(np.random.uniform(10))

2.4365658988959247


In [6]:
#WHY? (BROADCASTING)

arr=3*np.arange(10)
print(arr)
print(type(arr))
print(arr[2])

[ 0  3  6  9 12 15 18 21 24 27]
<class 'numpy.ndarray'>
6


# numpy array syntax

arr[rowindex,columnindex]

ex: arr[1,2]


In [9]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr[1,2])

[[1 2 3]
 [4 5 6]]
6


# Numpy arrays are mutable


In [10]:
arr[1,2]=99 
print(arr)

[[ 1  2  3]
 [ 4  5 99]]


# Numpy Slicing


In [11]:
arr=np.arange(10)

print(arr[::2])

print(arr[1:4])

print(arr[0:-4])

[0 2 4 6 8]
[1 2 3]
[0 1 2 3 4 5]


In [12]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr[:2,1:3])

[[2 3]
 [6 7]]


In [13]:
print(arr[1:2, :])

[[5 6 7 8]]


In [16]:
arr=np.array([[1,2],[3,4],[5,6]])
print(arr[2,1])
print(arr[[0,1,2],[0,1,0]])

6
[1 4 5]



# CRUD
  
  CREATE READ UPDATE DELETE

#    Numpy Maths

In [17]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(np.add(x,y))

print("*"*40)

print(np.subtract(x,y))

print("*"*40)

print(np.multiply(x,y))

print("*"*40)

print(np.divide(x,y))


[[ 6  8]
 [10 12]]
****************************************
[[-4 -4]
 [-4 -4]]
****************************************
[[ 5 12]
 [21 32]]
****************************************
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [18]:
# matrix multiplication

print(np.matmul(x,y))

print(np.dot(x,y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [19]:
x=np.array([[1,2],[3,4]])
print(np.sum(x))
print(np.sum(x,axis=0))  #column wise

print(np.sum(x,axis=1))  #row wise

10
[4 6]
[3 7]


In [20]:
print(np.min(x))
print(np.max(x))

1
4


# Transpose of a matrix

In [24]:
print(x)
print("*"*40)
print(x.T)

[[1 2]
 [3 4]]
****************************************
[[1 3]
 [2 4]]


In [23]:
np.exp(1)

2.718281828459045

In [25]:
np.exp(2)

7.38905609893065

# Numpy Statistics

In [26]:
x=np.array([160,146,180])
print(np.max(x))
print(np.min(x))

180
146


In [27]:
print(np.mean(x))#gives central tendency

print(np.median(x))  #even=(n/2)th +1
                      #odd=((n+1)/2)th

print(np.var(x))

print(np.std(x))


162.0
160.0
194.66666666666666
13.9522996909709


In [28]:
heights=np.array([160,180,176,184])

weights=np.array([50,78,45,51])

np.corrcoef(heights,weights)

array([[1.        , 0.30623607],
       [0.30623607, 1.        ]])

# NUMPY RESHAPE

In [30]:
arr=np.arange(0,50,5)
print(arr)

[ 0  5 10 15 20 25 30 35 40 45]


In [33]:
arr2d=arr.reshape(5,2)
print(arr2d)

[[ 0  5]
 [10 15]
 [20 25]
 [30 35]
 [40 45]]


In [34]:
arr2d=arr.reshape(2,5)
print(arr2d)

[[ 0  5 10 15 20]
 [25 30 35 40 45]]


In [36]:
arr=np.arange(5,50)
print(arr.shape)

(45,)


In [37]:
print(arr.reshape(3,3,5))

[[[ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]]

 [[35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]


In [38]:
#flatten()

print(arr.flatten())

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# Linespace,sorting,stacking,concatenate

In [40]:
np.sort(arr,axis=0)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
hstack
vstack