In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [ ]:
import numpy as np


#creating as simple array in numpy

arr=np.array([1,2,3,4])



In [3]:
import numpy as np

l=[1,2,3,4,5,6,7]
print(type(l))
arr=np.array(l)
print(type(arr))
print("list: ",l)
print("NP arr: ",arr)

<class 'list'>
<class 'numpy.ndarray'>
list:  [1, 2, 3, 4, 5, 6, 7]
NP arr:  [1 2 3 4 5 6 7]


In [ ]:
# nd array is called as "n-dimensional"

In [4]:
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
arr=np.arange(10)
print(arr)
print(type(arr))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [6]:
%%time
arr=np.arange(1000000)
arr=arr*arr

Wall time: 21.6 ms


In [7]:
%%time
lst=list(range(1000000))
for i in range(1000000):
    lst[i]*=lst[i]

Wall time: 198 ms


In [11]:
import numpy as np

arr=np.array([1,2,3,4])

print(arr.ndim)  #print no of dimensions

print(arr.shape)  #print shape

print(len(arr)) # print length

print(arr.dtype)  #print datatype

print(arr.itemsize)  #print item size in byte of each element

1
(4,)
4
int32
4


In [14]:
arr=np.array([[1,2,3],[4,5,6]])

print(arr)

print(arr.ndim)  #print no of dimensions

print(arr.shape)  #print shape

print(len(arr)) # print length

print(arr.dtype)  #print datatype

print(arr.itemsize)  #print item size in byte of each element

print(np.diag(arr))

[[1 2 3]
 [4 5 6]]
2
(2, 3)
2
int32
4
[1 5]


In [ ]:
FUNCTIONS OD CREATING ARRAY

In [15]:
arr=np.ones((3,3))
print(arr)
print(arr.dtype)
print(arr.itemsize)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
float64
8


In [16]:
arr=np.zeros((3,3))
print(arr)
print(arr.dtype)
print(arr.itemsize)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64
8


In [17]:
arr=np.eye(3)
print(arr)
print(arr.dtype)
print(arr.itemsize)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
float64
8


In [18]:
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
arr=np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [20]:
arr=np.arange(1,10,2)
print(arr)

[1 3 5 7 9]
